### ISSUE TITLE
failed to convert modified time to timestamp

### ISSUE THREAD

**Issue by jonathanstrong** [Peltoche/lsd#314]
## Expected behavior

`$ lsd path/to/dir` - expected directory listing. here is the output from the system `/bin/ls`:

```console
$ /bin/ls -lah public/
total 48K
drwxrwxr-x 8 jstrong jstrong 4.0K Dec 20 19:40 .
drwxrwxr-x 8 jstrong jstrong 4.0K Dec 20 19:39 ..
-rw-rw-r-- 1 jstrong jstrong 2.9K Dec 20 19:40 404.html
drwxrwxr-x 3 jstrong jstrong 4.0K Dec 20 19:40 categories
drwxrwxr-x 2 jstrong jstrong 4.0K Dec 20 19:40 css
drwxr-xr-x 2 jstrong jstrong 4.0K Aug 30  1754 images
-rw-rw-r-- 1 jstrong jstrong 3.0K Dec 20 19:40 index.html
-rw-rw-r-- 1 jstrong jstrong 2.5K Dec 20 19:40 index.xml
drwxrwxr-x 4 jstrong jstrong 4.0K Dec 20 19:40 posts
-rw-rw-r-- 1 jstrong jstrong  921 Dec 20 19:40 sitemap.xml
drwxrwxr-x 3 jstrong jstrong 4.0K Dec 20 19:40 tags
```

## Actual behavior

(note - I have `ls` aliased to `lsd`)

```console
$ RUST_BACKTRACE=full ls public/
thread 'main' panicked at 'failed to convert modified time to timestamp: SystemTimeError(6795364578.871345152s)', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x55fb2fec32c3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0e0a473856efea47
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55fb2febf23b - std::sys_common::backtrace::_print::ha353983cc21adc0d
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x55fb2fec2096 - std::panicking::default_hook::{{closure}}::h54fddbb00978e0de
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x55fb2fec1e14 - std::panicking::default_hook::h73563c5f4ed0a3ca
                               at src/libstd/panicking.rs:215
   4:     0x55fb2fec2740 - std::panicking::rust_panic_with_hook::h959128303aff731e
                               at src/libstd/panicking.rs:478
   5:     0x55fb2fec22c1 - std::panicking::continue_panic_fmt::hbde0d8cda48d551e
                               at src/libstd/panicking.rs:385
   6:     0x55fb2fec21a5 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x55fb2fed930c - core::panicking::panic_fmt::h0362772e3f8af39a
                               at src/libcore/panicking.rs:85
   8:     0x55fb2fe40055 - core::result::unwrap_failed::h5f468c85cfcfb186
   9:     0x55fb2fe3b38f - <lsd::meta::date::Date as core::convert::From<&'a std::fs::Metadata>>::from::hda86f7835eeae829
  10:     0x55fb2fe3cb21 - lsd::meta::Meta::from_path_recursive::h59004eb5f70df451
  11:     0x55fb2fe3d30d - lsd::meta::Meta::from_path_recursive::h59004eb5f70df451
  12:     0x55fb2fe5124c - lsd::core::Core::run::h1667c9af1ab7dc9d
  13:     0x55fb2fe3c16e - lsd::main::hffa363128f97ffed
  14:     0x55fb2fe4dfa2 - std::rt::lang_start::{{closure}}::hb2d5dc73bbf3390f
  15:     0x55fb2fec2142 - std::panicking::try::do_call::h05c1fd41e802b8be
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:297
  16:     0x55fb2fec5619 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:90
  17:     0x55fb2fec2c75 - std::rt::lang_start_internal::he4b2f7baa4ba6641
                               at src/libstd/panicking.rs:276
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  18:     0x55fb2fe3c251 - main
  19:     0x7fb7076dbb96 - __libc_start_main
  20:     0x55fb2fe36488 - _start
  21:                0x0 - <unknown>
```

```
$ ls --version
lsd 0.13.0
```

**Comment by jonathanstrong** [comment]
closing as I just updated to 0.16 and the crash no longer happens.
