### ISSUE TITLE
lsd panics

### ISSUE THREAD

**Issue by MaT1g3R** [Peltoche/lsd#387]
## Expected behavior

ls output:

```shell
❯ /bin/ls -la
total 4408
drwx------  32 umi umi    4096 Jun 23 19:14  .
drwxr-xr-x 112 umi umi    4096 Jun 24 12:32  ..
-rwxr-xr-x   1 umi umi  735908 Sep 16  2019 '5a35.ico'$'\247\375''='$'\356\324\373\206\362\300''^m'$'\330'
-rwxr-xr-x   1 umi umi  141853 Sep  4  2019  684e
-rwxr-xr-x   1 umi umi  106170 Jun 23  2019  8465
drwxr-xr-x   5 umi umi    4096 Jun 24 00:44  appcache
drwxr-xr-x   4 umi umi    4096 Apr 28  2018  bin
-rwxr-xr-x   1 umi umi   11384 Feb 10  2014  bin_steamdeps.py
-rw-r--r--   1 umi umi 2899552 Jun 23 19:14  bootstrap.tar.xz
drwxr-xr-x   6 umi umi    4096 Jun  3 18:57  clientui
drwxr-xr-x   5 umi umi    4096 May 29 19:36  compatibilitytools.d
drwxr-xr-x   5 umi umi    4096 Jun 24 00:23  config
drwxr-xr-x   4 umi umi    4096 Apr 29 18:32  controller_base
-rw-r--r--   1 umi umi       0 Jun 23 19:14  .crash
drwxr-xr-x   2 umi umi   32768 Jun 24 00:23  depotcache
drwxr-xr-x   2 umi umi    4096 Dec  8  2019  fontconfig
-rwxr-xr-x   1 umi umi     146 Jun  6  2019  fossilize_engine_filters.json
drwxr-xr-x   2 umi umi   16384 Jun  6 14:23  friends
drwxr-xr-x   3 umi umi   69632 Dec 16  2019  graphics
drwxr-xr-x   2 umi umi    4096 Jul 18  2019  html5app
-rw-r--r--   1 umi umi     736 Jan 19 19:53  installscriptevalutor_log.txt
drwxr-xr-x   2 umi umi    4096 Jun 23 19:14  legacycompat
drwx------   2 umi umi    4096 Jun  6 14:23  linux32
drwxr-xr-x   2 umi umi    4096 Jun  6 14:23  linux64
drwxr-xr-x   2 umi umi    4096 Jun 23 20:44  logs
drwxr-xr-x   3 umi umi    4096 Apr 28  2018  music
drwxr-xr-x   2 umi umi    4096 Jun  6 14:23  package
drwxr-xr-x   4 umi umi   20480 Jun  6 14:23  public
drwxr-xr-x   6 umi umi   20480 Jun  6 14:23  resource
drwxr-xr-x   2 umi umi    4096 May 15 18:51  servers
drwxr-xr-x   2 umi umi    4096 Jun 19  2019  singleapplauncher
drwxr-xr-x   2 umi umi    4096 Jul 18  2019  skins
-rw-r--r--   1 umi umi    2048 Apr 28  2018  ssfn2842615792614968837
drwxr-xr-x   4 umi umi    4096 Jul 18  2019  steam
drwxr-xr-x   9 umi umi    4096 May 29 20:15  steamapps
-rwxr-xr-x   1 umi umi     857 Oct  8  2013  steamdeps.txt
-rwxr-xr-x   1 umi umi    1316 Jul  9  2019  steam_msg.sh
-rwxr-xr-x   1 umi umi   21458 Apr 17 12:21  steam.sh
-rwxr-xr-x   1 umi umi   49827 May 31  2018  steam_subscriber_agreement.txt
drwxr-xr-x   6 umi umi    4096 Jun  6 14:23  steamui
drwxr-xr-x   3 umi umi    4096 Apr 28  2018  tenfoot
-rwxr-xr-x   1 umi umi     405 Dec 24  2013  ThirdPartyLegalNotices.css
-rwxr-xr-x   1 umi umi   25088 Dec 16  2013  ThirdPartyLegalNotices.doc
-rwxr-xr-x   1 umi umi  202978 May  6  2019  ThirdPartyLegalNotices.html
drwx------   6 umi umi    4096 Jun  6 14:23  ubuntu12_32
drwxr-xr-x   6 umi umi    4096 Jun  6 14:23  ubuntu12_64
drwxr-xr-x   3 umi umi    4096 Apr 28  2018  userdata
drwxr-xr-x   2 umi umi    4096 Apr 28 18:22  WINDOWSTEMPDIR_FONTCONFIG_CACHE

```

## Actual behavior
```shell
❯ env RUST_BACKTRACE=full lsd
thread 'main' panicked at 'failed to encode file name', /home/umi/.cargo/registry/src/github.com-1ecc6299db9ec823/lsd-0.17.0/src/meta/name.rs:25:17
stack backtrace:
   0:     0x5622eff0eb85 - backtrace::backtrace::libunwind::trace::hc3f32ba24d88242a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5622eff0eb85 - backtrace::backtrace::trace_unsynchronized::h1f075597100358e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5622eff0eb85 - std::sys_common::backtrace::_print_fmt::h4397782fec59f199
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5622eff0eb85 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39652f0242246c81
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5622eff342bc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5622eff0c453 - std::io::Write::write_fmt::haa03b5883ee9e297
                               at src/libstd/io/mod.rs:1537
   6:     0x5622eff11110 - std::sys_common::backtrace::_print::ha6d9bdf9f438acec
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5622eff11110 - std::sys_common::backtrace::print::ha1fba17a8e5f6bc7
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5622eff11110 - std::panicking::default_hook::{{closure}}::hbf9fcecd42c17d90
                               at src/libstd/panicking.rs:198
   9:     0x5622eff10e5c - std::panicking::default_hook::h39b8550780094336
                               at src/libstd/panicking.rs:218
  10:     0x5622eff11747 - std::panicking::rust_panic_with_hook::hc8b48ce48004c103
                               at src/libstd/panicking.rs:477
  11:     0x5622eff1134b - rust_begin_unwind
                               at src/libstd/panicking.rs:385
  12:     0x5622eff32c51 - core::panicking::panic_fmt::h78830ea6a34e7206
                               at src/libcore/panicking.rs:86
  13:     0x5622eff329e3 - core::option::expect_failed::hfc0519cb1ecb957f
                               at src/libcore/option.rs:1264
  14:     0x5622efde82b5 - lsd::meta::name::Name::new::h3c0031a8d295acfe
  15:     0x5622efe08a78 - lsd::meta::Meta::from_path::hdbad6c4b63fed7b7
  16:     0x5622efe06848 - lsd::meta::Meta::recurse_into::ha118d90b8585fba3
  17:     0x5622efe057ae - lsd::core::Core::run::hb36ec490bac54027
  18:     0x5622efde5db3 - lsd::main::h8f1bc5bdb7729bd9
  19:     0x5622efde2d83 - std::rt::lang_start::{{closure}}::h8afde2f98d8ca965
  20:     0x5622eff11b18 - std::rt::lang_start_internal::{{closure}}::hcf986077e2da8d6b
                               at src/libstd/rt.rs:52
  21:     0x5622eff11b18 - std::panicking::try::do_call::h076edd10f2a91969
                               at src/libstd/panicking.rs:297
  22:     0x5622eff11b18 - std::panicking::try::h54343dd1a9d830aa
                               at src/libstd/panicking.rs:274
  23:     0x5622eff11b18 - std::panic::catch_unwind::h81799eb8afacafdd
                               at src/libstd/panic.rs:394
  24:     0x5622eff11b18 - std::rt::lang_start_internal::hf4abd869024c3270
                               at src/libstd/rt.rs:51
  25:     0x5622efde6102 - main
  26:     0x7f7238ce2002 - __libc_start_main
  27:     0x5622efddf18e - _start
  28:                0x0 - <unknown>

```

**Comment by Peltoche** [comment]
Hello @MaT1g3R ,

Thanks for the report. Can you give us your lsd version by running `lsd --version` please?

**Comment by MaT1g3R** [comment]
```
❯ lsd --version
lsd 0.17.0
```

**Comment by zwpaper** [comment]
I noticed that there is a confused file `'5a35.ico'$'\247\375''='$'\356\324\373\206\362\300''^m'$'\330'`

can you try to `ls` it?

like 

```
lsd '5a35.ico'$'\247\375''='$'\356\324\373\206\362\300''^m'$'\330'
```

or copy the dir and leave it alone then do `lsd`?

@MaT1g3R

**Comment by MaT1g3R** [comment]
ls output:

```
❯ /bin/ls -l 5a35.ico\Xa7\Xfd=\Xee\Xd4\Xfb\X86\Xf2\Xc0\^m\Xd8 
-rwxr-xr-x 1 umi umi 735908 Sep 16  2019 '5a35.ico'$'\247\375''='$'\356\324\373\206\362\300''^m'$'\330'
```

lsd output:

```
❯ env RUST_BACKTRACE=full lsd 5a35.ico\Xa7\Xfd=\Xee\Xd4\Xfb\X86\Xf2\Xc0\^m\Xd8 
thread 'main' panicked at 'unexpected invalid UTF-8 code point', /home/umi/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.1/src/args/arg_matches.rs:217:17
stack backtrace:
   0:     0x557d0744bb85 - backtrace::backtrace::libunwind::trace::hc3f32ba24d88242a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x557d0744bb85 - backtrace::backtrace::trace_unsynchronized::h1f075597100358e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x557d0744bb85 - std::sys_common::backtrace::_print_fmt::h4397782fec59f199
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x557d0744bb85 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39652f0242246c81
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x557d074712bc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x557d07449453 - std::io::Write::write_fmt::haa03b5883ee9e297
                               at src/libstd/io/mod.rs:1537
   6:     0x557d0744e110 - std::sys_common::backtrace::_print::ha6d9bdf9f438acec
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x557d0744e110 - std::sys_common::backtrace::print::ha1fba17a8e5f6bc7
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x557d0744e110 - std::panicking::default_hook::{{closure}}::hbf9fcecd42c17d90
                               at src/libstd/panicking.rs:198
   9:     0x557d0744de5c - std::panicking::default_hook::h39b8550780094336
                               at src/libstd/panicking.rs:218
  10:     0x557d0744e747 - std::panicking::rust_panic_with_hook::hc8b48ce48004c103
                               at src/libstd/panicking.rs:477
  11:     0x557d0744e34b - rust_begin_unwind
                               at src/libstd/panicking.rs:385
  12:     0x557d0746fc51 - core::panicking::panic_fmt::h78830ea6a34e7206
                               at src/libcore/panicking.rs:86
  13:     0x557d0746f9e3 - core::option::expect_failed::hfc0519cb1ecb957f
                               at src/libcore/option.rs:1264
  14:     0x557d0742e871 - clap::args::arg_matches::ArgMatches::values_of::to_str_slice::hf0d88168d0a0f519
  15:     0x557d0742e897 - <clap::args::arg_matches::OsValues as core::iter::traits::iterator::Iterator>::next::h62546cef00131082
  16:     0x557d07335ee0 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h9afbdfd3bbd1486f
  17:     0x557d07322ca3 - lsd::main::h8f1bc5bdb7729bd9
  18:     0x557d0731fd83 - std::rt::lang_start::{{closure}}::h8afde2f98d8ca965
  19:     0x557d0744eb18 - std::rt::lang_start_internal::{{closure}}::hcf986077e2da8d6b
                               at src/libstd/rt.rs:52
  20:     0x557d0744eb18 - std::panicking::try::do_call::h076edd10f2a91969
                               at src/libstd/panicking.rs:297
  21:     0x557d0744eb18 - std::panicking::try::h54343dd1a9d830aa
                               at src/libstd/panicking.rs:274
  22:     0x557d0744eb18 - std::panic::catch_unwind::h81799eb8afacafdd
                               at src/libstd/panic.rs:394
  23:     0x557d0744eb18 - std::rt::lang_start_internal::hf4abd869024c3270
                               at src/libstd/rt.rs:51
  24:     0x557d07323102 - main
  25:     0x7f23e1c1c152 - __libc_start_main
  26:     0x557d0731c18e - _start
  27:                0x0 - <unknown>
```

@zwpaper

**Comment by zwpaper** [comment]
@MaT1g3R May I ask how do u create this file? I try to touch one and failed

![image](https://user-images.githubusercontent.com/3764335/92678277-39c36600-f358-11ea-8300-25c855bd3783.png)

**Comment by MaT1g3R** [comment]
@zwpaper  I believe the file was originally created by steam, but I am able to re-create the file like so:

```bash
❯ python -c "import pathlib; pathlib.Path('5a35.ico\udca7\udcfd=\udcee\udcd4\udcfb\udc86\udcf2\udcc0^m\udcd8').touch()"

❯ lsd
thread 'main' panicked at 'failed to encode file name', /home/umi/.cargo/registry/src/github.com-1ecc6299db9ec823/lsd-0.17.0/src/meta/name.rs:25:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zwpaper** [comment]
@MaT1g3R I have reproduced the file name, It can not create in macOS, but created in Linux.
I will dive into it soon, I believe this should be a UTF-8 encoding problem

**Comment by zwpaper** [comment]
the panic is fixed, but the output is a little bit different like the one you post here.

the utf8 code in the filename is reserved for utf-16(https://en.wikipedia.org/wiki/UTF-16#U+D800_to_U+DFFF), and rust will check this by default.

Following the rust way, we display the reserved chars as �
