### ISSUE TITLE
Non-deterministic panic (broken pipe) using --tree option

### ISSUE THREAD

**Issue by lsbloxx** [Peltoche/lsd#97]
## Expected behavior
```
/tmp/tmp.EHAycWKNJu $ RUST_BACKTRACE=1 lsd --tree | head -n 5
├── example-file-1
├── example-file-10
├── example-file-11
├── example-file-12
├── example-file-13
```

lsd does not panic. :)

## Actual behavior
```
/tmp/tmp.EHAycWKNJu $ RUST_BACKTRACE=1 lsd --tree | head -n 5
├── example-file-1
├── example-file-10
├── example-file-11
├── example-file-12
├── example-file-13
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:700:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:210
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:224
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:487
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:394
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:349
   7: std::io::stdio::_print
             at src/libstd/io/stdio.rs:700
             at src/libstd/io/stdio.rs:709
   8: lsd::display::Display::print_tree_row
   9: lsd::core::Core::display_as_tree
  10: lsd::core::Core::run_inner
  11: lsd::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:306
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:285
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
```

Interestingly, this bug seems to be non-deterministic. If I repeat the command multiple times, the process terminates sometimes with and sometimes without a panic.

**Comment by Peltoche** [comment]
Hi @lsbloxx ,

Thanks for the report. You just found a pretty funny bug:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:700:9
```
It seems that the bug is due to your `head -n 5` command. I guess that once the `head` command have received its 5 lines it will close the pipe but `lsd` continue to write on it and so `println` panics.

I will try to fix this asap.

**Comment by lsbloxx** [comment]
Thanks for you quick support! Keep up your good work! :)
